[package]
name = "pqcrypto-python"
version = "1.0.0"
edition = "2021"
rust-version = "1.85"
license = "Apache-2.0"
repository = "https://github.com/backbone-hq/pqcrypto"
authors = ["Backbone Technologies Ltd. <root@backbone.dev>"]
description = "Python bindings for post-quantum cryptography."
publish = false

[lints.rust]
unsafe_code = "forbid"
non_camel_case_types = "allow"

[lints.clippy]
unwrap_used = "warn"

[lib]
name = "pqcrypto"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.29", features = [
  "extension-module",
  "abi3",
  "abi3-py39",
] }
backbone-ml-kem = "0.2.0"
backbone-sntrup = "0.2.0"
backbone-ml-dsa = "0.2.0"
backbone-sphincs = "0.2.0"
backbone-mceliece = "0.2.0"
backbone-hqc = "0.2.0"

[profile.release]
strip = true
