name: CI

on:
  push:
    branches:
      - master
      - experimentation
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup UV
        uses: astral-sh/setup-uv@v5
        with:
          python-version: 3.13

      - name: Install dependencies
        run: uv sync --frozen --extra dev

      - name: Check code style
        run: uvx ruff check

      - name: Compile binaries
        run: uv run compile.py

      - name: Run tests
        run: uv run pytest tests

  # Reference: https://cibuildwheel.pypa.io/en/stable/setup/#github-actions
  build-wheels:
    name: build-wheels-${{ matrix.os }}
    needs:
      - check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13, macos-14, ubuntu-24.04-arm]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup UV
        uses: astral-sh/setup-uv@v5
        with:
          python-version: 3.13

      - name: Install dependencies
        run: uv sync --frozen --extra dev

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.23.2
        with:
          output-dir: dist

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifact-wheel-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./dist/*.whl
          retention-days: 1

  publish:
    needs:
      - build-wheels
    runs-on: ubuntu-latest

    environment: release
    permissions:
      id-token: write

    steps:
      - name: Download built packages
        uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
